head(df)
glimpse(df)
summary(df)
anyNA(df)
data <- df %>% select(Blood.Pressure, BMI, Income, Country)
head(data)
library(tidyr)
data <- data %>% separate(Blood.Pressure, into = c('Systolic', 'Diastolic'), sep ='/')
head(data)
